killbill/killbill-commons

- jdbi/pom.xml
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DaoConfig.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceConnectionPoolingType.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java
- jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
- queue/src/main/java/org/killbill/queue/InTransaction.java
mostly need a fix for #8 and the ability to set connection init SQL (mostly for the osgi pool)
... also removed BoneCP (not really production ready) - best to avoid
p.s. C3P0 might need to be updated to 0.9.5 for the init SQL to work
**TODO** update master pom dependencies - C3P0 (0.9.5 final), HikariCP and remove BoneCP
> support for dao.initSql + working dao.minIdle with HikariCP

- metrics/pom.xml
- metrics/src/main/java/org/killbill/commons/metrics/MetricTag.java
- metrics/src/main/java/org/killbill/commons/metrics/TimedResource.java
- pom.xml
- skeleton/pom.xml
- skeleton/src/main/java/org/killbill/commons/skeleton/metrics/ResourceTimer.java
- skeleton/src/main/java/org/killbill/commons/skeleton/metrics/TimedResourceInterceptor.java
- skeleton/src/main/java/org/killbill/commons/skeleton/metrics/TimedResourceListener.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/StatsModule.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/ResourceTimerTest.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/TestResourceTimer.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/TestTimedResourceInterceptor.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/TimedResourceInterceptorTest.java
Intercept resources with `@TimedResource` annotation and time execution.
Creates a timer metric for annotated resource method with the following dimensions:
* Resource Path (from @Path annotation on the class)
* Name (either from the @TimedResource annotation or from the method name)
* Tags (from parameters annotated with @MetricTag)
* Http Method
* Response status group (2xx, 3xx, etc)
The unit tests cover the Guice Listener for creating interceptors and the Interceptor itself.
Here's an example of a generated metric name: `kb_resource./1.0/kb/accounts.getAccountByKey.GET.4xx.404`
Right now, this is different from the plugin generated metrics, since it doesn't have the `killbill-service` prefix, so this is something we could add to keep things consistent: …
> @TimedResource metrics

- queue/src/main/resources/org/killbill/bus/dao/PersistentBusSqlDao.sql.stg
- queue/src/main/resources/org/killbill/notificationq/dao/NotificationSqlDao.sql.stg
Updates to queries in https://github.com/killbill/killbill/issues/703 cause an exception when running against PostgreSQL: `operator does not exist: datetime < text`.  Consider the following behavior under PostgreSQL 9.6.
```
CREATE DOMAIN datetime AS timestamp without time zone;
CREATE TABLE test_table (datetime_value DATETIME);
```
The definition of datetime is from the bridge at https://github.com/killbill/killbill/blob/master/util/src/main/resources/org/killbill/billing/util/ddl-postgresql.sql.
Under some conditions PostgreSQL will perform an implicit conversion between text and dates.  This statement will execute successfully:
```
SELECT * FROM test_table WHERE datetime_value < '2100-01-01';
```
These statements however will throw `operator does not exist`:
```
SELECT * FROM …
```
> Update queries to be compatible with Postgres

- jdbi/pom.xml
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceConnectionPoolingType.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java
- jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
Currently, Kill Bill supports the use of either [c3p0](http://www.mchange.com/projects/c3p0/) or [HikariCP](https://brettwooldridge.github.io/HikariCP/) for pooling database connections. In either case, database connections are managed by software running in the same JVM that Kill Bill is
running in.
It would be nice to have the option of configuring Kill Bill so that it doesn't try to pool database connections. This would make it easier to use external database connection pools like [PGBouncer](http://pgbouncer.github.io/).
See also [killbill-platform pull request 18](https://github.com/killbill/killbill-platform/pull/18).
> Support unpooled database connections

- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DaoConfig.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java
By default, HikariCP shuts down the pool if it encounters an error during initialization.
Guice swallows this error, Kill Bill stops its startup sequence and no information is returned to the user.
This patch introduces a new config property to control this behavior and changes the default:
* If false (new default), the startup sequence continues. Subsequent attempts to retrieve a connection through `HikariDataSource.getConnection` will log an exception if any (the Kill Bill startup sequence continues nonetheless)
* If true (previous behavior), the connection exception is now logged but Guice swallows it and Kill Bill stops its startup sequence
This new default should help debug connectivity issues when provisioning cloud environments.
@sbrossie Could you test this patch to see if it …
> jdbi: add new config property org.killbill.dao.initializationFailFast

- embeddeddb/common/src/main/java/org/killbill/commons/embeddeddb/EmbeddedDB.java
- embeddeddb/common/src/main/java/org/killbill/commons/embeddeddb/GenericStandaloneDB.java
- embeddeddb/mysql/pom.xml
- embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/KillBillMariaDbDataSource.java
- embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/MySQLStandaloneDB.java
- embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/MySQLEmbeddedDB.java
- embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/TestKillBillMariaDbDataSource.java
- embeddeddb/postgresql/src/main/java/org/killbill/commons/embeddeddb/postgresql/PostgreSQLStandaloneDB.java
- jdbi/pom.xml
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DaoConfig.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java
- jdbi/src/main/java/org/skife/jdbi/v2/DBI.java
- jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
- pom.xml
- queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java
- queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java
- queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueueService.java
- queue/src/main/java/org/killbill/queue/InTransaction.java
* Make sure DBI caches are used for the queues APIs
* Ensure prepared statements are cached (server-side) by default (regression with recent MariaDB driver upgrade)
> jdbi: perf updates

- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DaoConfig.java
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java
This puts connections in read-only mode as a hint to the driver to enable database optimizations.
> jdbi: make HikariCP read-only state configurable

- queue/src/main/java/org/killbill/queue/api/PersistentQueueEntryLifecycleState.java
- queue/src/main/java/org/killbill/queue/dispatching/CallableCallbackBase.java
- queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java
- queue/src/main/java/org/killbill/queue/retry/RetryableInternalException.java
- queue/src/main/java/org/killbill/queue/retry/RetryableService.java
- queue/src/test/java/org/killbill/bus/TestRetries.java
- queue/src/test/java/org/killbill/notificationq/TestNotificationQueue.java
The original event to be retried will be mark as RETRIED.
Subsequent retry events (org.killbill.queue.retry.RetryNotificationEvent) will also
be marked as RETRIED, except the last one (GIVEN_UP).
Error count will always be 0 for all of these.
> queue: introduce specific states for user initiated retries

- queue/pom.xml
Create an artifact with our forked version of JDBI shaded. That way, projects can depend on it without having to worry about a conflicting JDBI version.
Note: make sure to exclude the killbill-jdbi transitive dependency.
> queue: create jdbi-shaded artifact

- queue/src/main/java/org/killbill/queue/DBBackedQueue.java
- queue/src/main/java/org/killbill/queue/dao/QueueSqlDao.java
- queue/src/main/resources/org/killbill/queue/dao/QueueSqlDao.sql.stg
- queue/src/test/java/org/killbill/notificationq/dao/TestNotificationSqlDao.java
Regarding `insertEntry` failing, I'm not even sure it's possible it would silently fail?
> queue: remove usage of LAST_INSERT_ID

- queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java
- queue/src/main/java/org/killbill/bus/InMemoryPersistentBus.java
- queue/src/main/java/org/killbill/bus/api/PersistentBusConfig.java
- queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java
- queue/src/main/java/org/killbill/notificationq/NotificationQueueDispatcher.java
- queue/src/main/java/org/killbill/notificationq/api/NotificationQueueConfig.java
- queue/src/main/java/org/killbill/queue/DefaultQueueLifecycle.java
- queue/src/main/java/org/killbill/queue/DefaultReaper.java
- queue/src/main/java/org/killbill/queue/api/PersistentQueueConfig.java
- queue/src/main/java/org/killbill/queue/api/QueueLifecycle.java
- queue/src/main/java/org/killbill/queue/api/Reaper.java
- queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java
- queue/src/test/java/org/killbill/bus/TestInMemoryEventBus.java
- queue/src/test/java/org/killbill/notificationq/MockNotificationQueue.java
- queue/src/test/java/org/killbill/queue/TestDBBackedQueueWithInflightQ.java
- queue/src/test/java/org/killbill/queue/TestLoadDBBackedQueue.java
- queue/src/test/java/org/killbill/queue/TestReaper.java
- queue/src/test/java/org/killbill/queue/TestReaperIntegration.java
- queue/src/test/java/org/killbill/queue/dispatching/TestDispatcher.java
Make timeout configurable to wait for executors threads to complete.
Some handlers can take a long time (e.g. Analytics plugin handlers) and the default hardcoded 5s value isn't always enough in practice. This can result in leaving `IN_PROCESSING` entries on disk if the shutdown sequence doesn't wait for these threads to finish.
As part of this, the shutdown sequence was revisited too. With the previous implementation, even if the shutdown sequence waits for these threads to finish, `IN_PROCESSING` entries could still be left on disk if the completion threads are
stopped before all jobs in the dispatcher queue are done.
I've also bumped the default timeout from 5s to 15s (5s might be a bit aggressive, even for core Kill Bill handlers).
It's a ☕ kind of review 😸 Might be easier to checkout …
> queue: revisit shutdown sequence

- queue/src/main/java/org/killbill/queue/DBBackedQueueWithPolling.java
Remove the condition which prevents reaped entries to be reinserted (so as to allow them to be processed).
> queue: Fix issue with reaper in POLLING mode

- .github/workflows/ci.yml
- .github/workflows/snapshot.yml
- .github/workflows/sync.yml
Publish SNAPSHOT builds to Sonatype.
The name will contain the short `sha`. For instance, for this commit, the version is `0.25.1-febe09c-SNAPSHOT`.
This can be found on the job page:
Someone working on a feature should now be able to simply specify in the Kill Bill pom.xml:
```
<killbill-commons.version>0.25.1-febe09c-SNAPSHOT</killbill-commons.version>
```
This also introduces shared jobs from https://github.com/killbill/gh-actions-shared (the CI job has also been migrated as a proof of concept for more complex workflows).
> .github: add snapshot job

- config-magic/pom.xml
- queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java
Tested manually using breakpoints.
> queue: ensure the MDC is always cleared after dispatching an entry

- embeddeddb/mysql/pom.xml
- embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/KillBillMariaDbDataSource.java
- embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/MySQLStandaloneDB.java
- embeddeddb/mysql/src/test/java/io/airlift/testing/mysql/HackedTestingMySqlServer.java
- embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/MySQLEmbeddedDB.java
- embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/TestKillBillMariaDbDataSource.java
- jdbi/src/main/java/org/killbill/commons/jdbi/mapper/LowerToCamelBeanMapper.java
- jdbi/src/main/java/org/killbill/commons/jdbi/statement/SmartFetchSize.java
- jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
- pom.xml
* `permitMysqlScheme` is now required in the jdbc url to support the `jdbc:mysql` scheme.
* The first byte is at position 1 when calling `blob.getBytes` (per the spec). Not sure why we never noticed the issue, I suspect some codepaths aren't exercised.
* Streaming doesn't rely on the `Integer.MIN_VALUE` hint anymore. I've verified streaming still works as expected (a `StreamingResult` is returned of size 1 and fetches data as needed unlike when `CompleteResult` is used, where everything is loaded in memory).
> embeddeddb: jdbi: support for mariadb-java-client 3.0.4

- queue/src/main/java/org/killbill/CreatorName.java
This will fail the build when upgrading spotbugs-maven-plugin to 4.6.0.0.
> queue: address SSD_DO_NOT_USE_INSTANCE_LOCK_ON_SHARED_STATIC_DATA error

- config-magic/pom.xml
- jdbi/pom.xml
Addresses:
```
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M6:test: java.lang.NoSuchMethodError: 'void org.apache.maven.surefire.api.testset.RunOrderParameters.<init>(java.lang.String, java.io.File, java.lang.Long)'
```
> junit: update surefire-junit47 to 3.0.0-M6

- embeddeddb/h2/src/main/java/org/killbill/commons/embeddeddb/h2/H2EmbeddedDB.java
Close the database pool ASAP to make sure the database is never re-opened by HikariCP background threads after the SHUTDOWN command is sent.
Before https://github.com/killbill/killbill-commons/pull/118, we could close the MVStore explicitly, but this isn't possible anymore.
> h2: fix race condition on stop

- README.md
- queue/src/test/java/org/killbill/bus/TestInMemoryEventBus.java
- utils/pom.xml
- utils/src/main/java/org/killbill/commons/utils/annotation/VisibleForTesting.java
- utils/src/main/java/org/killbill/commons/utils/cache/Cache.java
- utils/src/main/java/org/killbill/commons/utils/cache/DefaultCache.java
- utils/src/main/java/org/killbill/commons/utils/cache/DefaultSynchronizedCache.java
- utils/src/main/java/org/killbill/commons/utils/cache/TimedValue.java
- utils/src/test/java/org/killbill/commons/utils/cache/TestDefaultCache.java
Add cache implementation.
Note for `TestInMemoryEventBus` :
- Test methods mixed with "slow" and "fast" test group. Decided to make it "fast" because it supposed to be "fast" tests
- add `alwaysRun = true` because sometimes test failed with NPE (for example NPE in line 153, or 158)
> 1615 killbill utils cache

- utils/README.md
- utils/src/main/java/org/killbill/commons/eventbus/AllowConcurrentEvents.java
- utils/src/main/java/org/killbill/commons/eventbus/CatchableSubscriberExceptionHandler.java
- utils/src/main/java/org/killbill/commons/eventbus/DeadEvent.java
- utils/src/main/java/org/killbill/commons/eventbus/DefaultCatchableSubscriberExceptionsHandler.java
- utils/src/main/java/org/killbill/commons/eventbus/Dispatcher.java
- utils/src/main/java/org/killbill/commons/eventbus/EventBus.java
- utils/src/main/java/org/killbill/commons/eventbus/EventBusException.java
- utils/src/main/java/org/killbill/commons/eventbus/LoggingHandler.java
- utils/src/main/java/org/killbill/commons/eventbus/Subscribe.java
- utils/src/main/java/org/killbill/commons/eventbus/Subscriber.java
- utils/src/main/java/org/killbill/commons/eventbus/SubscriberExceptionContext.java
- utils/src/main/java/org/killbill/commons/eventbus/SubscriberExceptionHandler.java
- utils/src/main/java/org/killbill/commons/eventbus/SubscriberRegistry.java
- utils/src/main/java/org/killbill/commons/eventbus/package-info.java
- utils/src/main/java/org/killbill/commons/utils/Primitives.java
- utils/src/main/java/org/killbill/commons/utils/TypeToken.java
- utils/src/main/java/org/killbill/commons/utils/collect/ConcatenatedIterator.java
- utils/src/main/java/org/killbill/commons/utils/collect/Iterators.java
- utils/src/main/java/org/killbill/commons/utils/concurrent/DirectExecutor.java
- utils/src/test/java/org/killbill/commons/eventbus/SetupTestEventBusPostWithException.java
- utils/src/test/java/org/killbill/commons/eventbus/StringCatcher.java
- utils/src/test/java/org/killbill/commons/eventbus/TestDispatcher.java
- utils/src/test/java/org/killbill/commons/eventbus/TestEventBus.java
- utils/src/test/java/org/killbill/commons/eventbus/TestEventBusPostWithException.java
- utils/src/test/java/org/killbill/commons/eventbus/TestReentrantEvents.java
- utils/src/test/java/org/killbill/commons/eventbus/TestSubscriber.java
- utils/src/test/java/org/killbill/commons/eventbus/TestSubscriberRegistry.java
- utils/src/test/java/org/killbill/commons/utils/TestTypeToken.java
fork guava's EventBus to killbill-commons `utils` module under `org.killbill.commons.eventbus` package.
- `postWithException()` already merged to `EventBus`
- `AsyncEventBus` get removed
- Use util's `Cache` instead of guava's `Cache`.
- killbill previously `TestEventBusThatThrowsException` and `TestMultiThreadedEventBusThatThrowsException` merged to `TestEventBusPostWithException`
- We have `CatchableSubscriberExceptionHandler` interface if `EventBus` client want to work with `postWithException()`
- Different with original Guava's `EventBus`, `DirectExecutor.INSTANCE` and `Dispatcher.immediate()` is default value for our `EventBus` executor and dispatcher.
> 1615 killbill utils eventbus

- automaton/pom.xml
- automaton/src/main/java/org/killbill/automaton/DefaultStateMachine.java
- automaton/src/main/java/org/killbill/automaton/DefaultStateMachineConfig.java
- automaton/src/main/java/org/killbill/automaton/dot/DOTBuilder.java
- automaton/src/main/java/org/killbill/automaton/dot/DefaultStateMachineConfigDOTGenerator.java
- automaton/src/test/java/org/killbill/automaton/TestStateMachine.java
- automaton/src/test/java/org/killbill/automaton/dot/TestDOTBuilder.java
- skeleton/pom.xml
- skeleton/src/main/java/org/killbill/commons/skeleton/listeners/GuiceServletContextListener.java
- skeleton/src/main/java/org/killbill/commons/skeleton/metrics/ResourceTimer.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/BaseServerModuleBuilder.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/ConfigModule.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/GuiceServletContainer.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/JMXModule.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/JerseyBaseServerModule.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/TimedInterceptionService.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/TestResourceTimer.java
- skeleton/src/test/java/org/killbill/commons/skeleton/metrics/TestTimedResourceInterceptor.java
- skeleton/src/test/java/org/killbill/commons/skeleton/modules/HelloResource.java
- skeleton/src/test/java/org/killbill/commons/skeleton/modules/TestJerseyBaseServerModule.java
- utils/src/main/java/org/killbill/commons/utils/collect/EvictingQueue.java
- utils/src/test/java/org/killbill/commons/utils/collect/TestEvictingQueue.java
- xmlloader/pom.xml
- xmlloader/src/main/java/org/killbill/xmlloader/UriAccessor.java
- xmlloader/src/test/java/org/killbill/xmlloader/TestXMLSchemaGenerator.java
This is the last PR for #1615 work in `killbill-commons` repository. After this, `killbill-commons` will be Guava-free. Notes:
1. `DefaultStateMachine` line ~164 : Refactor from `IllegalStateException` to `NoSuchElementException`, otherwise `TestStateMachine` failed. This is caused by `Optional#get()` in Guava and java 8 throw different exception.
2. `DefaultStateMachineConfig` line ~121 : Refactor from `IllegalStateException` to `NoSuchElementException` . Same reason as point 1.
> 1615 remove guava part 4

- automaton/src/test/java/org/killbill/automaton/dot/TestDOTBuilder.java
simplify `@Test` annotation and add diamond to `new TreeSet<>()` declaration.
Commit that actually fix the problem in #4 is previous commit: 3979ffe2.
> Fix TestDOTBuilder is failing

- config-magic/pom.xml
- jdbi/pom.xml
- jdbi/src/main/java/org/killbill/commons/jdbi/guice/DBIProvider.java
- metrics/pom.xml
- metrics/src/main/java/org/killbill/commons/metrics/health/KillBillHealthCheckRegistry.java
- pom.xml
- `DBIProvider` and `KillBillHealthCheckRegistry` still use Guice `@Inject` annotation
- remove unused dependency
- update `killbill-oss-version`, in attempt to fix `killbill` repository build.
> 1615 remove guice and update oss

- config-magic/src/main/java/org/skife/config/ConfigurationObjectFactory.java
- config-magic/src/main/java/org/skife/config/SimplePropertyConfigSource.java
Related issue: https://github.com/killbill/killbill-commons/issues/113
- All modification explained in each commit. 
- Leave `NP_BOOLEAN_RETURN_NULL` in `DefaultCoercibles.BOOLEAN_COERCER`, because I assume that this is should be failed (and throw exception) if user set something like `some.other.config.useReadDb=Truer`
> 115 address spotbugs config magic

- embeddeddb/common/src/main/java/org/killbill/commons/embeddeddb/EmbeddedDB.java
- embeddeddb/h2/pom.xml
- embeddeddb/h2/src/main/java/org/killbill/commons/embeddeddb/h2/H2EmbeddedDB.java
Related issue: https://github.com/killbill/killbill-commons/issues/113
- apply to `embeddeddb` and all submodules.
- All modification explained in each commit. 
- Leave `EmbeddedDB.datasource` as is, with `EI_EXPOSE_REP` in getter and `EI_EXPOSE_REP2` in its setter.
> address spotbugs in embeddeddb

- locker/pom.xml
- locker/spotbugs-exclude.xml
- locker/src/main/java/org/killbill/commons/locker/GlobalLockBase.java
- locker/src/main/java/org/killbill/commons/locker/GlobalLockerBaseWithDao.java
- queue/pom.xml
- queue/spotbugs-exclude.xml
- queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java
- queue/src/main/java/org/killbill/bus/dispatching/BusCallableCallback.java
- queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java
- queue/src/main/java/org/killbill/notificationq/NotificationQueueDispatcher.java
- queue/src/main/java/org/killbill/notificationq/dispatching/NotificationCallableCallback.java
- queue/src/main/java/org/killbill/queue/DBBackedQueue.java
- queue/src/main/java/org/killbill/queue/DefaultQueueLifecycle.java
- queue/src/main/java/org/killbill/queue/QueueObjectMapper.java
- queue/src/main/java/org/killbill/queue/dispatching/CallableCallbackBase.java
- queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java
- queue/src/main/java/org/killbill/queue/dispatching/EventEntryDeserializer.java
- queue/src/main/java/org/killbill/queue/retry/RetryableService.java
- queue/src/test/java/org/killbill/notificationq/MockNotificationQueue.java
- queue/src/test/java/org/killbill/notificationq/MockNotificationQueueService.java
See: https://github.com/killbill/killbill-commons/issues/113. This PR affected locker and queue modules. 
Commit in Oct 8 may contains casual update. However, commit in Oct 11 probably need attention:
- These are the commits: https://github.com/killbill/killbill-commons/commit/d9c3565534d9ee13eac482890877fb8e32271b4e , https://github.com/killbill/killbill-commons/commit/4a667c04acf7afc4b7de552f7cf6e9bb612c30e9 , https://github.com/killbill/killbill-commons/commit/a32ba65646fb9176a6cd3511889deb222a425ee0 , https://github.com/killbill/killbill-commons/commit/f665f34da6e8c75f149c7e6e98198ad4a041830b .
- To wrap it up: we use `ObjectReader` + `ObjectWriter` (that obtained via `ObjectMapper`) instead of `ObjectMapper`. See more [here](https://stackoverflow.com/a/3909846/554958).
- Tested …
> Commons 113 spotbugs in locker and queue

- automaton/pom.xml
- automaton/spotbugs-exclude.xml
- automaton/src/main/java/org/killbill/automaton/DefaultStateMachine.java
- automaton/src/main/java/org/killbill/automaton/DefaultStateMachineConfig.java
- skeleton/spotbugs-exclude.xml
- xmlloader/pom.xml
- xmlloader/spotbugs-exclude.xml
- xmlloader/src/main/java/org/killbill/xmlloader/ValidationError.java
- xmlloader/src/main/java/org/killbill/xmlloader/ValidationException.java
Some notes: 
- I don't think we need copy constructor for [jaxb classes](https://github.com/killbill/killbill-commons/commit/b23e678d9ccbce7a86ddd742a63d7e88304ad13e).
- I call `clone()` to getter/setter to array [based attributes](https://github.com/killbill/killbill-commons/commit/6551d89dbc8b0120e9668ba103fc3db337e11f2e).
- This is last PR for #113 in killbill-commons.
> Commons 113 spotbugs in xmlloader and automaton

- embeddeddb/h2/src/main/java/org/killbill/commons/embeddeddb/h2/H2EmbeddedDB.java
for CI debugging purpose. Better solution might be added by reverting this, once we get more context. Decided to set connection pool to 100 instead, although the branch name is "set to 50".
> change jdbcConnectionPool.setMaxConnections() to 50

- queue/src/main/java/org/killbill/queue/DBBackedQueue.java
- queue/src/test/java/org/killbill/TestSetup.java
- queue/src/test/java/org/killbill/queue/TestReaper.java
- queue/src/test/java/org/killbill/queue/TestReaperIntegration.java
This is a fix to address existing stuck entries to be reaped even in a single node deployment. See https://github.com/killbill/killbill-commons/issues/169#issuecomment-2050797495
I tried this on an existing deployment showing the issue by pushing this jar:
```
select * from notifications where effective_date < NOW();
+-----------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+---------------------+---------------------------------------------+---------------------------------------------+---------------------------+------------------+-------------+------- …
```
> queue: Allow stuck entries (same node) to be reaped. See #169

- config-magic/pom.xml
- metrics-api/pom.xml
- queue/src/main/java/org/killbill/bus/api/PersistentBusConfig.java
- queue/src/main/java/org/killbill/notificationq/api/NotificationQueueConfig.java
Updated default queue mode to `POLLING` as discussed [here](https://github.com/killbill/killbill-aviate-plugin/issues/40#issuecomment-2798801111). 
~~Edit: Moving to `DRAFT` as there are [ci failures](https://github.com/killbill/killbill-commons/actions/runs/14442833600).~~
Moving back to `IN_REVIEW` as there are no ci failures now.
> Update default queue mode to POLLING

- config-magic/src/main/java/org/skife/config/AugmentedConfigurationObjectFactory.java
- config-magic/src/main/java/org/skife/config/ConfigurationObjectFactory.java
- config-magic/src/main/java/org/skife/config/RuntimeConfigRegistry.java
- jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
- queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java
- queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueueService.java
- queue/src/test/java/org/killbill/TestSetup.java
- queue/src/test/java/org/killbill/bus/TestLoadDefaultPersistentBus.java
- skeleton/src/main/java/org/killbill/commons/skeleton/modules/ConfigModule.java
* Made ConfigurationObjectFactory package private to limit external usage
* Enhanced AugmentedConfigurationObjectFactory to collect runtime configuration values and store them in RuntimeConfigRegistry.
> ConfigurationObjectFactory changes

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .idea/misc.xml
- automaton/pom.xml
- clock/pom.xml
- concurrent/pom.xml
- config-magic/pom.xml
- embeddeddb/common/pom.xml
- embeddeddb/h2/pom.xml
- embeddeddb/mysql/pom.xml
- embeddeddb/pom.xml
- embeddeddb/postgresql/pom.xml
- jdbi/pom.xml
- locker/pom.xml
- metrics-api/pom.xml
- metrics/pom.xml
- pom.xml
- queue/pom.xml
- skeleton/pom.xml
- utils/pom.xml
- xmlloader/pom.xml
Changes to fix release failure. snapshot release is also fixed. With this change, I've released version  `0.26.10` of `killbill-commons`.  If changes looks good, I would suggest "squash and merge" as there are a lot of intermediate commits for debugging purpose.
> Fix release failure
