jdbi/src/main/java/org/killbill/commons/jdbi/mapper/LowerToCamelBeanMapper.java
Cache transformation detection at initialization time, to avoid costly isAssignableFrom() calls at runtime.
=> jdbi: optimize LowerToCamelBeanMapper

clock/src/test/java/org/killbill/clock/ClockMock.java, queue/src/main/java/org/killbill/notificationq/dao/NotificationEventModelDao.java, queue/src/main/java/org/killbill/queue/DBBackedQueue.java, queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java
* clock: log time when we reset the clock
* queue: log full event in DEBUG entries
* queue: put the user token in the MDC
=> Add debug context

queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java, queue/src/main/java/org/killbill/notificationq/NotificationQueueDispatcher.java, queue/src/main/java/org/killbill/queue/DBBackedQueue.java, queue/src/main/java/org/killbill/queue/dispatching/Dispatcher.java, queue/src/test/java/org/killbill/notificationq/dao/TestNotificationSqlDao.java, queue/src/test/java/org/killbill/queue/TestDBBackedQueue.java, queue/src/test/java/org/killbill/queue/TestLoadDBBackedQueue.java
* Review log.debug entries
* Print SQL Warnings in DEBUG mode
=> queue: make debugging easier

queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java, queue/src/main/java/org/killbill/notificationq/api/NotificationQueue.java, queue/src/main/java/org/killbill/queue/DBBackedQueue.java, queue/src/test/java/org/killbill/notificationq/MockNotificationQueue.java, queue/src/test/java/org/killbill/notificationq/TestNotificationQueue.java
This is for https://github.com/killbill/killbill/issues/864.
=> queue: add NotificationQueue#removeFutureNotificationsForSearchKeys API

jdbi/src/main/java/org/skife/jdbi/v2/MappingRegistry.java
killbill/killbill#335
killbill/killbill#972
=>  Add the possibility to bypass mapping registry cache

automaton/src/main/java/org/killbill/automaton/DefaultLinkStateMachine.java, automaton/src/main/java/org/killbill/automaton/DefaultOperation.java, automaton/src/main/java/org/killbill/automaton/DefaultState.java, automaton/src/main/java/org/killbill/automaton/DefaultStateMachine.java, automaton/src/main/java/org/killbill/automaton/DefaultStateMachineConfig.java, automaton/src/main/java/org/killbill/automaton/DefaultTransition.java, xmlloader/src/main/java/org/killbill/xmlloader/ValidatingConfig.java, xmlloader/src/main/java/org/killbill/xmlloader/ValidationError.java, xmlloader/src/main/java/org/killbill/xmlloader/ValidationErrors.java, xmlloader/src/main/java/org/killbill/xmlloader/XMLLoader.java, xmlloader/src/test/java/org/killbill/xmlloader/TestXMLLoader.java, xmlloader/src/test/java/org/killbill/xmlloader/TestXMLWriter.java
This is in preparation for caching improvements in Kill Bill.
=> automaton, xmlloader: make objects serializable

jdbi/src/main/java/org/skife/jdbi/v2/GeneratedKeys.java, jdbi/src/main/java/org/skife/jdbi/v2/PreparedBatch.java, jdbi/src/main/java/org/skife/jdbi/v2/sqlobject/BatchHandler.java
This is an adaptation of the upstream code.
=> jdbi: batch execute and generate keys

queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java, queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java, queue/src/main/java/org/killbill/queue/InTransaction.java
Signed-off-by: Pierre-Alexandre Meyer <pierre@mouraf.org>
=> queue: don't swallow exceptions

queue/src/main/java/org/killbill/bus/InMemoryPersistentBus.java
This fixes https://github.com/killbill/killbill/issues/1299.
=> queue: fix InMemoryPersistentBus init sequence

NEWS, embeddeddb/common/pom.xml, embeddeddb/common/src/main/java/org/killbill/commons/embeddeddb/EmbeddedDB.java, embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/KillBillMariaDbDataSource.java, embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/MySQLStandaloneDB.java, jdbi/pom.xml, jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java, jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java, pom.xml, queue/pom.xml
This addresses wave 2 of killbill/killbill-oss-parent#34.
=> Dependencies updates

jdbi/src/main/java/org/killbill/commons/jdbi/hikari/KillBillMetricsTracker.java, metrics-api/src/main/java/org/killbill/commons/metrics/api/MetricRegistry.java, metrics-api/src/main/java/org/killbill/commons/metrics/impl/NoOpMetricRegistry.java, metrics/pom.xml, metrics/src/main/java/org/killbill/commons/metrics/dropwizard/KillBillCodahaleMetricRegistry.java, metrics/src/main/java/org/killbill/commons/metrics/guice/GaugeInjectionListener.java, metrics/src/main/java/org/killbill/commons/metrics/servlets/HealthCheckJacksonModule.java, metrics/src/main/java/org/killbill/commons/metrics/servlets/HealthCheckServlet.java, metrics/src/main/java/org/killbill/commons/metrics/servlets/MetricsJacksonModule.java, metrics/src/main/java/org/killbill/commons/metrics/servlets/MetricsServlet.java, queue/src/main/java/org/killbill/queue/DBBackedQueueWithInflightQueue.java, queue/src/main/java/org/killbill/queue/DefaultQueueLifecycle.java
=> Abstract away Dropwizard Metrics - bug fixes

pom.xml, skeleton/pom.xml
See:
* https://github.com/google/guice/wiki/Guice501
* https://github.com/google/guice/wiki/Guice510
=> pom.xml: update Guice to 5.1.0

clock/pom.xml, jdbi/pom.xml, jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceConnectionPoolingType.java, jdbi/src/main/java/org/killbill/commons/jdbi/guice/DataSourceProvider.java, jdbi/src/test/java/org/killbill/commons/jdbi/guice/TestDataSourceProvider.java
We haven't used c3p0 for many years.
=> Remove c3p0 support

skeleton/pom.xml, skeleton/src/test/java/org/killbill/commons/skeleton/modules/TestJerseyBaseServerModule.java
This is part of https://github.com/killbill/killbill/issues/1640.
=> skeleton: remove AsyncHttpClient dependency

.idea/encodings.xml, README.md, pom.xml, utils/README.md, utils/pom.xml, utils/spotbugs-exclude.xml, utils/src/main/java/org/killbill/commons/utils/Joiner.java, utils/src/main/java/org/killbill/commons/utils/Preconditions.java, utils/src/main/java/org/killbill/commons/utils/Strings.java, utils/src/main/java/org/killbill/commons/utils/collect/AbstractIterator.java, utils/src/main/java/org/killbill/commons/utils/collect/Iterables.java, utils/src/main/java/org/killbill/commons/utils/collect/Iterators.java, utils/src/main/java/org/killbill/commons/utils/collect/MultiValueHashMap.java, utils/src/main/java/org/killbill/commons/utils/collect/MultiValueMap.java, utils/src/main/java/org/killbill/commons/utils/collect/Sets.java, utils/src/main/java/org/killbill/commons/utils/collect/TransformedIterator.java, utils/src/main/java/org/killbill/commons/utils/io/ByteStreams.java, utils/src/main/java/org/killbill/commons/utils/io/CharStreams.java, utils/src/main/java/org/killbill/commons/utils/io/IOUtils.java, utils/src/main/java/org/killbill/commons/utils/io/Resources.java, utils/src/main/java/org/killbill/commons/utils/math/IntMath.java, utils/src/main/java/org/killbill/commons/utils/math/Ints.java, utils/src/main/java/org/killbill/commons/utils/net/HttpHeaders.java, utils/src/test/java/org/killbill/commons/utils/TestStrings.java, utils/src/test/java/org/killbill/commons/utils/collect/KeyValue.java, utils/src/test/java/org/killbill/commons/utils/collect/TestIterables.java, utils/src/test/java/org/killbill/commons/utils/collect/TestIterators.java, utils/src/test/java/org/killbill/commons/utils/collect/TestMultiValueHashMap.java, utils/src/test/java/org/killbill/commons/utils/collect/TestSets.java
contains classes from `util` module in killbill repository and moved to new module named `killbill-commons-utils`.
=> 1615 killbill commons utils

concurrent/pom.xml, concurrent/src/main/java/org/killbill/commons/profiling/ProfilingData.java, embeddeddb/mysql/pom.xml, embeddeddb/mysql/src/main/java/org/killbill/commons/embeddeddb/mysql/KillBillMariaDbDataSource.java, embeddeddb/mysql/src/test/java/io/airlift/testing/mysql/HackedEmbeddedMySql.java, embeddeddb/mysql/src/test/java/io/airlift/testing/mysql/HackedTestingMySqlServer.java, embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/MySQLEmbeddedDB.java, embeddeddb/mysql/src/test/java/org/killbill/commons/embeddeddb/mysql/TestKillBillMariaDbDataSource.java, embeddeddb/postgresql/pom.xml, embeddeddb/postgresql/src/test/java/org/killbill/commons/embeddeddb/postgresql/KillBillEmbeddedPostgreSql.java, embeddeddb/postgresql/src/test/java/org/killbill/commons/embeddeddb/postgresql/KillBillTestingPostgreSqlServer.java, utils/src/main/java/org/killbill/commons/utils/MapJoiner.java, utils/src/main/java/org/killbill/commons/utils/StandardSystemProperty.java, utils/src/main/java/org/killbill/commons/utils/collect/Iterables.java, utils/src/main/java/org/killbill/commons/utils/collect/Iterators.java, utils/src/main/java/org/killbill/commons/utils/concurrent/ThreadFactoryBuilder.java, utils/src/test/java/org/killbill/commons/utils/TestMapJoiner.java, utils/src/test/java/org/killbill/commons/utils/concurrent/TestThreadFactoryBuilder.java
_Note: This PR seems "disconnected work" since I have another works for `EventBus`, also `Cache` work in `killbill`. But I was working on this when waiting for build, test, PR etc. I choose to send PR now to avoid too much merge conflict_ 
Start removing Guava classes in `killbill-commons`.
=> 1615 remove guava part 1

queue/pom.xml, queue/src/main/java/org/killbill/CreatorName.java, queue/src/main/java/org/killbill/bus/DefaultPersistentBus.java, queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueue.java, queue/src/main/java/org/killbill/notificationq/DefaultNotificationQueueService.java, queue/src/main/java/org/killbill/queue/DBBackedQueue.java, queue/src/main/java/org/killbill/queue/DBBackedQueueWithPolling.java, queue/src/main/java/org/killbill/queue/InTransaction.java, queue/src/main/java/org/killbill/queue/retry/RetryableSubscriber.java, queue/src/test/java/org/killbill/TestSetup.java, queue/src/test/java/org/killbill/bus/TestPersistentEventBus.java, queue/src/test/java/org/killbill/notificationq/MockNotificationQueue.java, queue/src/test/java/org/killbill/notificationq/TestNotificationQueue.java, queue/src/test/java/org/killbill/notificationq/dao/TestNotificationSqlDao.java, queue/src/test/java/org/killbill/queue/TestLoadDBBackedQueue.java, queue/src/test/java/org/killbill/queue/TestReaper.java, utils/src/main/java/org/killbill/commons/utils/cache/DefaultCache.java, utils/src/main/java/org/killbill/commons/utils/cache/DefaultSynchronizedCache.java, utils/src/main/java/org/killbill/commons/utils/io/Files.java, utils/src/main/java/org/killbill/commons/utils/reflect/AbstractInvocationHandler.java
[This commit](https://github.com/killbill/killbill-commons/commit/d5f41176184f5a74eb2a3e408dc3bd002ac8fb94) may nothing to do with removing Guava, but add it here to use in `killbill-platform` later.
=> 1615 remove guava part 3

config-magic/src/main/java/org/skife/config/DefaultCoercibles.java, embeddeddb/common/pom.xml, embeddeddb/common/spotbugs-exclude.xml, embeddeddb/common/src/main/java/org/killbill/commons/embeddeddb/EmbeddedDB.java, metrics-api/spotbugs-exclude.xml, metrics-api/src/main/java/org/killbill/commons/health/impl/HealthyResult.java, metrics-api/src/main/java/org/killbill/commons/health/impl/UnhealthyResult.java, metrics-api/src/main/java/org/killbill/commons/metrics/impl/NoOpMetricRegistry.java
Some things missed in previous work of https://github.com/killbill/killbill-commons/issues/113. This PR address them.
=> Commons 133 fix missed spotbugs config

metrics/spotbugs-exclude.xml, metrics/src/main/java/org/killbill/commons/metrics/guice/annotation/ListAnnotationResolver.java
fix [spotbug issue](https://github.com/killbill/killbill-commons/issues/113) in `killbill-metrics` module.
=> Commons 113 fix spotbugs issue in metrics

queue/src/main/java/org/killbill/queue/DBBackedQueue.java
Original issue: https://github.com/killbill/killbill-commons/issues/162
Report from community: https://github.com/killbill/killbill-commons/issues/47#issuecomment-1486317130
=> fix reaper over-reporting late entries

config-magic/src/main/java/org/skife/config/AugmentedConfigurationObjectFactory.java, config-magic/src/main/java/org/skife/config/RuntimeConfigRegistry.java
* Updated RuntimeConfigRegistry to track properties by their source.
* Updated AugmentedConfigurationObjectFactory to populate properties along with their sources.
=> Expose runtime config properties by source
